language: android
sudo: required
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - nvm install 8
  - node --version
  - npm i typescript@next react-native-cli -g --progress=false
install:
  - npm install
  - chmod +x ./prepare.sh
script: ./prepare.sh
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-16
node_js:
  - "8"