language: android
sudo: required
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - nvm install 12
  - node --version
  - npm i typescript react-native-cli -g --progress=false
install:
  - npm install
  - chmod +x ./prepare.sh
script: ./prepare.sh
android:
  components:
    - build-tools-26.0.3
    - android-26
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-19
node_js:
  - "12"